// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: ISO 4217 Snapshot

import 'currency.dart';

const Map<String, CurrencyMetadata> iso4217Currencies = {
  'AED': CurrencyMetadata(
    alpha3Code: 'AED',
    numericCode: 784,
    name: 'UAE Dirham',
    minorUnitExponent: 2,
  ),
  'AFN': CurrencyMetadata(
    alpha3Code: 'AFN',
    numericCode: 971,
    name: 'Afghani',
    minorUnitExponent: 2,
  ),
  'ALL': CurrencyMetadata(
    alpha3Code: 'ALL',
    numericCode: 8,
    name: 'Lek',
    minorUnitExponent: 2,
  ),
  'AMD': CurrencyMetadata(
    alpha3Code: 'AMD',
    numericCode: 51,
    name: 'Armenian Dram',
    minorUnitExponent: 2,
  ),
  'ANG': CurrencyMetadata(
    alpha3Code: 'ANG',
    numericCode: 532,
    name: 'Netherlands Antillean Guilder',
    minorUnitExponent: 2,
  ),
  'AOA': CurrencyMetadata(
    alpha3Code: 'AOA',
    numericCode: 973,
    name: 'Kwanza',
    minorUnitExponent: 2,
  ),
  'ARS': CurrencyMetadata(
    alpha3Code: 'ARS',
    numericCode: 32,
    name: 'Argentine Peso',
    minorUnitExponent: 2,
  ),
  'AUD': CurrencyMetadata(
    alpha3Code: 'AUD',
    numericCode: 36,
    name: 'Australian Dollar',
    minorUnitExponent: 2,
  ),
  'AWG': CurrencyMetadata(
    alpha3Code: 'AWG',
    numericCode: 533,
    name: 'Aruban Florin',
    minorUnitExponent: 2,
  ),
  'AZN': CurrencyMetadata(
    alpha3Code: 'AZN',
    numericCode: 944,
    name: 'Azerbaijan Manat',
    minorUnitExponent: 2,
  ),
  'BAM': CurrencyMetadata(
    alpha3Code: 'BAM',
    numericCode: 977,
    name: 'Convertible Mark',
    minorUnitExponent: 2,
  ),
  'BBD': CurrencyMetadata(
    alpha3Code: 'BBD',
    numericCode: 52,
    name: 'Barbados Dollar',
    minorUnitExponent: 2,
  ),
  'BDT': CurrencyMetadata(
    alpha3Code: 'BDT',
    numericCode: 50,
    name: 'Taka',
    minorUnitExponent: 2,
  ),
  'BGN': CurrencyMetadata(
    alpha3Code: 'BGN',
    numericCode: 975,
    name: 'Bulgarian Lev',
    minorUnitExponent: 2,
  ),
  'BHD': CurrencyMetadata(
    alpha3Code: 'BHD',
    numericCode: 48,
    name: 'Bahraini Dinar',
    minorUnitExponent: 3,
  ),
  'BIF': CurrencyMetadata(
    alpha3Code: 'BIF',
    numericCode: 108,
    name: 'Burundi Franc',
    minorUnitExponent: 0,
  ),
  'BMD': CurrencyMetadata(
    alpha3Code: 'BMD',
    numericCode: 60,
    name: 'Bermudian Dollar',
    minorUnitExponent: 2,
  ),
  'BND': CurrencyMetadata(
    alpha3Code: 'BND',
    numericCode: 96,
    name: 'Brunei Dollar',
    minorUnitExponent: 2,
  ),
  'BOB': CurrencyMetadata(
    alpha3Code: 'BOB',
    numericCode: 68,
    name: 'Boliviano',
    minorUnitExponent: 2,
  ),
  'BRL': CurrencyMetadata(
    alpha3Code: 'BRL',
    numericCode: 986,
    name: 'Brazilian Real',
    minorUnitExponent: 2,
  ),
  'BSD': CurrencyMetadata(
    alpha3Code: 'BSD',
    numericCode: 44,
    name: 'Bahamian Dollar',
    minorUnitExponent: 2,
  ),
  'BTN': CurrencyMetadata(
    alpha3Code: 'BTN',
    numericCode: 64,
    name: 'Ngultrum',
    minorUnitExponent: 2,
  ),
  'BWP': CurrencyMetadata(
    alpha3Code: 'BWP',
    numericCode: 72,
    name: 'Pula',
    minorUnitExponent: 2,
  ),
  'BYN': CurrencyMetadata(
    alpha3Code: 'BYN',
    numericCode: 933,
    name: 'Belarusian Ruble',
    minorUnitExponent: 2,
  ),
  'BZD': CurrencyMetadata(
    alpha3Code: 'BZD',
    numericCode: 84,
    name: 'Belize Dollar',
    minorUnitExponent: 2,
  ),
  'CAD': CurrencyMetadata(
    alpha3Code: 'CAD',
    numericCode: 124,
    name: 'Canadian Dollar',
    minorUnitExponent: 2,
  ),
  'CDF': CurrencyMetadata(
    alpha3Code: 'CDF',
    numericCode: 976,
    name: 'Congolese Franc',
    minorUnitExponent: 2,
  ),
  'CHF': CurrencyMetadata(
    alpha3Code: 'CHF',
    numericCode: 756,
    name: 'Swiss Franc',
    minorUnitExponent: 2,
  ),
  'CLP': CurrencyMetadata(
    alpha3Code: 'CLP',
    numericCode: 152,
    name: 'Chilean Peso',
    minorUnitExponent: 0,
  ),
  'CNY': CurrencyMetadata(
    alpha3Code: 'CNY',
    numericCode: 156,
    name: 'Yuan Renminbi',
    minorUnitExponent: 2,
  ),
  'COP': CurrencyMetadata(
    alpha3Code: 'COP',
    numericCode: 170,
    name: 'Colombian Peso',
    minorUnitExponent: 2,
  ),
  'CRC': CurrencyMetadata(
    alpha3Code: 'CRC',
    numericCode: 188,
    name: 'Costa Rican Colon',
    minorUnitExponent: 2,
  ),
  'CUP': CurrencyMetadata(
    alpha3Code: 'CUP',
    numericCode: 192,
    name: 'Cuban Peso',
    minorUnitExponent: 2,
  ),
  'CVE': CurrencyMetadata(
    alpha3Code: 'CVE',
    numericCode: 132,
    name: 'Cabo Verde Escudo',
    minorUnitExponent: 2,
  ),
  'CZK': CurrencyMetadata(
    alpha3Code: 'CZK',
    numericCode: 203,
    name: 'Czech Koruna',
    minorUnitExponent: 2,
  ),
  'DJF': CurrencyMetadata(
    alpha3Code: 'DJF',
    numericCode: 262,
    name: 'Djibouti Franc',
    minorUnitExponent: 0,
  ),
  'DKK': CurrencyMetadata(
    alpha3Code: 'DKK',
    numericCode: 208,
    name: 'Danish Krone',
    minorUnitExponent: 2,
  ),
  'DOP': CurrencyMetadata(
    alpha3Code: 'DOP',
    numericCode: 214,
    name: 'Dominican Peso',
    minorUnitExponent: 2,
  ),
  'DZD': CurrencyMetadata(
    alpha3Code: 'DZD',
    numericCode: 12,
    name: 'Algerian Dinar',
    minorUnitExponent: 2,
  ),
  'EGP': CurrencyMetadata(
    alpha3Code: 'EGP',
    numericCode: 818,
    name: 'Egyptian Pound',
    minorUnitExponent: 2,
  ),
  'ERN': CurrencyMetadata(
    alpha3Code: 'ERN',
    numericCode: 232,
    name: 'Nakfa',
    minorUnitExponent: 2,
  ),
  'ETB': CurrencyMetadata(
    alpha3Code: 'ETB',
    numericCode: 230,
    name: 'Ethiopian Birr',
    minorUnitExponent: 2,
  ),
  'EUR': CurrencyMetadata(
    alpha3Code: 'EUR',
    numericCode: 978,
    name: 'Euro',
    minorUnitExponent: 2,
  ),
  'FJD': CurrencyMetadata(
    alpha3Code: 'FJD',
    numericCode: 242,
    name: 'Fiji Dollar',
    minorUnitExponent: 2,
  ),
  'FKP': CurrencyMetadata(
    alpha3Code: 'FKP',
    numericCode: 238,
    name: 'Falkland Islands Pound',
    minorUnitExponent: 2,
  ),
  'GBP': CurrencyMetadata(
    alpha3Code: 'GBP',
    numericCode: 826,
    name: 'Pound Sterling',
    minorUnitExponent: 2,
  ),
  'GEL': CurrencyMetadata(
    alpha3Code: 'GEL',
    numericCode: 981,
    name: 'Lari',
    minorUnitExponent: 2,
  ),
  'GHS': CurrencyMetadata(
    alpha3Code: 'GHS',
    numericCode: 936,
    name: 'Ghana Cedi',
    minorUnitExponent: 2,
  ),
  'GIP': CurrencyMetadata(
    alpha3Code: 'GIP',
    numericCode: 292,
    name: 'Gibraltar Pound',
    minorUnitExponent: 2,
  ),
  'GMD': CurrencyMetadata(
    alpha3Code: 'GMD',
    numericCode: 270,
    name: 'Dalasi',
    minorUnitExponent: 2,
  ),
  'GNF': CurrencyMetadata(
    alpha3Code: 'GNF',
    numericCode: 324,
    name: 'Guinean Franc',
    minorUnitExponent: 0,
  ),
  'GTQ': CurrencyMetadata(
    alpha3Code: 'GTQ',
    numericCode: 320,
    name: 'Quetzal',
    minorUnitExponent: 2,
  ),
  'GYD': CurrencyMetadata(
    alpha3Code: 'GYD',
    numericCode: 328,
    name: 'Guyana Dollar',
    minorUnitExponent: 2,
  ),
  'HKD': CurrencyMetadata(
    alpha3Code: 'HKD',
    numericCode: 344,
    name: 'Hong Kong Dollar',
    minorUnitExponent: 2,
  ),
  'HNL': CurrencyMetadata(
    alpha3Code: 'HNL',
    numericCode: 340,
    name: 'Lempira',
    minorUnitExponent: 2,
  ),
  'HRK': CurrencyMetadata(
    alpha3Code: 'HRK',
    numericCode: 191,
    name: 'Kuna',
    minorUnitExponent: 2,
  ),
  'HTG': CurrencyMetadata(
    alpha3Code: 'HTG',
    numericCode: 332,
    name: 'Gourde',
    minorUnitExponent: 2,
  ),
  'HUF': CurrencyMetadata(
    alpha3Code: 'HUF',
    numericCode: 348,
    name: 'Forint',
    minorUnitExponent: 2,
  ),
  'IDR': CurrencyMetadata(
    alpha3Code: 'IDR',
    numericCode: 360,
    name: 'Rupiah',
    minorUnitExponent: 2,
  ),
  'ILS': CurrencyMetadata(
    alpha3Code: 'ILS',
    numericCode: 376,
    name: 'New Israeli Sheqel',
    minorUnitExponent: 2,
  ),
  'INR': CurrencyMetadata(
    alpha3Code: 'INR',
    numericCode: 356,
    name: 'Indian Rupee',
    minorUnitExponent: 2,
  ),
  'IQD': CurrencyMetadata(
    alpha3Code: 'IQD',
    numericCode: 368,
    name: 'Iraqi Dinar',
    minorUnitExponent: 3,
  ),
  'IRR': CurrencyMetadata(
    alpha3Code: 'IRR',
    numericCode: 364,
    name: 'Iranian Rial',
    minorUnitExponent: 2,
  ),
  'ISK': CurrencyMetadata(
    alpha3Code: 'ISK',
    numericCode: 352,
    name: 'Iceland Krona',
    minorUnitExponent: 0,
  ),
  'JMD': CurrencyMetadata(
    alpha3Code: 'JMD',
    numericCode: 388,
    name: 'Jamaican Dollar',
    minorUnitExponent: 2,
  ),
  'JOD': CurrencyMetadata(
    alpha3Code: 'JOD',
    numericCode: 400,
    name: 'Jordanian Dinar',
    minorUnitExponent: 3,
  ),
  'JPY': CurrencyMetadata(
    alpha3Code: 'JPY',
    numericCode: 392,
    name: 'Yen',
    minorUnitExponent: 0,
  ),
  'KES': CurrencyMetadata(
    alpha3Code: 'KES',
    numericCode: 404,
    name: 'Kenyan Shilling',
    minorUnitExponent: 2,
  ),
  'KGS': CurrencyMetadata(
    alpha3Code: 'KGS',
    numericCode: 417,
    name: 'Som',
    minorUnitExponent: 2,
  ),
  'KHR': CurrencyMetadata(
    alpha3Code: 'KHR',
    numericCode: 116,
    name: 'Riel',
    minorUnitExponent: 2,
  ),
  'KMF': CurrencyMetadata(
    alpha3Code: 'KMF',
    numericCode: 174,
    name: 'Comorian Franc',
    minorUnitExponent: 0,
  ),
  'KPW': CurrencyMetadata(
    alpha3Code: 'KPW',
    numericCode: 408,
    name: 'North Korean Won',
    minorUnitExponent: 2,
  ),
  'KRW': CurrencyMetadata(
    alpha3Code: 'KRW',
    numericCode: 410,
    name: 'Won',
    minorUnitExponent: 0,
  ),
  'KWD': CurrencyMetadata(
    alpha3Code: 'KWD',
    numericCode: 414,
    name: 'Kuwaiti Dinar',
    minorUnitExponent: 3,
  ),
  'KYD': CurrencyMetadata(
    alpha3Code: 'KYD',
    numericCode: 136,
    name: 'Cayman Islands Dollar',
    minorUnitExponent: 2,
  ),
  'KZT': CurrencyMetadata(
    alpha3Code: 'KZT',
    numericCode: 398,
    name: 'Tenge',
    minorUnitExponent: 2,
  ),
  'LAK': CurrencyMetadata(
    alpha3Code: 'LAK',
    numericCode: 418,
    name: 'Lao Kip',
    minorUnitExponent: 2,
  ),
  'LBP': CurrencyMetadata(
    alpha3Code: 'LBP',
    numericCode: 422,
    name: 'Lebanese Pound',
    minorUnitExponent: 2,
  ),
  'LKR': CurrencyMetadata(
    alpha3Code: 'LKR',
    numericCode: 144,
    name: 'Sri Lanka Rupee',
    minorUnitExponent: 2,
  ),
  'LRD': CurrencyMetadata(
    alpha3Code: 'LRD',
    numericCode: 430,
    name: 'Liberian Dollar',
    minorUnitExponent: 2,
  ),
  'LSL': CurrencyMetadata(
    alpha3Code: 'LSL',
    numericCode: 426,
    name: 'Loti',
    minorUnitExponent: 2,
  ),
  'LYD': CurrencyMetadata(
    alpha3Code: 'LYD',
    numericCode: 434,
    name: 'Libyan Dinar',
    minorUnitExponent: 3,
  ),
  'MAD': CurrencyMetadata(
    alpha3Code: 'MAD',
    numericCode: 504,
    name: 'Moroccan Dirham',
    minorUnitExponent: 2,
  ),
  'MDL': CurrencyMetadata(
    alpha3Code: 'MDL',
    numericCode: 498,
    name: 'Moldovan Leu',
    minorUnitExponent: 2,
  ),
  'MGA': CurrencyMetadata(
    alpha3Code: 'MGA',
    numericCode: 969,
    name: 'Malagasy Ariary',
    minorUnitExponent: 2,
  ),
  'MKD': CurrencyMetadata(
    alpha3Code: 'MKD',
    numericCode: 807,
    name: 'Denar',
    minorUnitExponent: 2,
  ),
  'MMK': CurrencyMetadata(
    alpha3Code: 'MMK',
    numericCode: 104,
    name: 'Kyat',
    minorUnitExponent: 2,
  ),
  'MNT': CurrencyMetadata(
    alpha3Code: 'MNT',
    numericCode: 496,
    name: 'Tugrik',
    minorUnitExponent: 2,
  ),
  'MOP': CurrencyMetadata(
    alpha3Code: 'MOP',
    numericCode: 446,
    name: 'Pataca',
    minorUnitExponent: 2,
  ),
  'MRU': CurrencyMetadata(
    alpha3Code: 'MRU',
    numericCode: 929,
    name: 'Ouguiya',
    minorUnitExponent: 2,
  ),
  'MUR': CurrencyMetadata(
    alpha3Code: 'MUR',
    numericCode: 480,
    name: 'Mauritius Rupee',
    minorUnitExponent: 2,
  ),
  'MVR': CurrencyMetadata(
    alpha3Code: 'MVR',
    numericCode: 462,
    name: 'Rufiyaa',
    minorUnitExponent: 2,
  ),
  'MWK': CurrencyMetadata(
    alpha3Code: 'MWK',
    numericCode: 454,
    name: 'Malawi Kwacha',
    minorUnitExponent: 2,
  ),
  'MXN': CurrencyMetadata(
    alpha3Code: 'MXN',
    numericCode: 484,
    name: 'Mexican Peso',
    minorUnitExponent: 2,
  ),
  'MYR': CurrencyMetadata(
    alpha3Code: 'MYR',
    numericCode: 458,
    name: 'Malaysian Ringgit',
    minorUnitExponent: 2,
  ),
  'MZN': CurrencyMetadata(
    alpha3Code: 'MZN',
    numericCode: 943,
    name: 'Mozambique Metical',
    minorUnitExponent: 2,
  ),
  'NAD': CurrencyMetadata(
    alpha3Code: 'NAD',
    numericCode: 516,
    name: 'Namibia Dollar',
    minorUnitExponent: 2,
  ),
  'NGN': CurrencyMetadata(
    alpha3Code: 'NGN',
    numericCode: 566,
    name: 'Naira',
    minorUnitExponent: 2,
  ),
  'NIO': CurrencyMetadata(
    alpha3Code: 'NIO',
    numericCode: 558,
    name: 'Cordoba Oro',
    minorUnitExponent: 2,
  ),
  'NOK': CurrencyMetadata(
    alpha3Code: 'NOK',
    numericCode: 578,
    name: 'Norwegian Krone',
    minorUnitExponent: 2,
  ),
  'NPR': CurrencyMetadata(
    alpha3Code: 'NPR',
    numericCode: 524,
    name: 'Nepalese Rupee',
    minorUnitExponent: 2,
  ),
  'NZD': CurrencyMetadata(
    alpha3Code: 'NZD',
    numericCode: 554,
    name: 'New Zealand Dollar',
    minorUnitExponent: 2,
  ),
  'OMR': CurrencyMetadata(
    alpha3Code: 'OMR',
    numericCode: 512,
    name: 'Rial Omani',
    minorUnitExponent: 3,
  ),
  'PAB': CurrencyMetadata(
    alpha3Code: 'PAB',
    numericCode: 590,
    name: 'Balboa',
    minorUnitExponent: 2,
  ),
  'PEN': CurrencyMetadata(
    alpha3Code: 'PEN',
    numericCode: 604,
    name: 'Sol',
    minorUnitExponent: 2,
  ),
  'PGK': CurrencyMetadata(
    alpha3Code: 'PGK',
    numericCode: 598,
    name: 'Kina',
    minorUnitExponent: 2,
  ),
  'PHP': CurrencyMetadata(
    alpha3Code: 'PHP',
    numericCode: 608,
    name: 'Philippine Peso',
    minorUnitExponent: 2,
  ),
  'PKR': CurrencyMetadata(
    alpha3Code: 'PKR',
    numericCode: 586,
    name: 'Pakistan Rupee',
    minorUnitExponent: 2,
  ),
  'PLN': CurrencyMetadata(
    alpha3Code: 'PLN',
    numericCode: 985,
    name: 'Zloty',
    minorUnitExponent: 2,
  ),
  'PYG': CurrencyMetadata(
    alpha3Code: 'PYG',
    numericCode: 600,
    name: 'Guarani',
    minorUnitExponent: 0,
  ),
  'QAR': CurrencyMetadata(
    alpha3Code: 'QAR',
    numericCode: 634,
    name: 'Qatari Rial',
    minorUnitExponent: 2,
  ),
  'RON': CurrencyMetadata(
    alpha3Code: 'RON',
    numericCode: 946,
    name: 'Romanian Leu',
    minorUnitExponent: 2,
  ),
  'RSD': CurrencyMetadata(
    alpha3Code: 'RSD',
    numericCode: 941,
    name: 'Serbian Dinar',
    minorUnitExponent: 2,
  ),
  'RUB': CurrencyMetadata(
    alpha3Code: 'RUB',
    numericCode: 643,
    name: 'Russian Ruble',
    minorUnitExponent: 2,
  ),
  'RWF': CurrencyMetadata(
    alpha3Code: 'RWF',
    numericCode: 646,
    name: 'Rwanda Franc',
    minorUnitExponent: 0,
  ),
  'SAR': CurrencyMetadata(
    alpha3Code: 'SAR',
    numericCode: 682,
    name: 'Saudi Riyal',
    minorUnitExponent: 2,
  ),
  'SBD': CurrencyMetadata(
    alpha3Code: 'SBD',
    numericCode: 90,
    name: 'Solomon Islands Dollar',
    minorUnitExponent: 2,
  ),
  'SCR': CurrencyMetadata(
    alpha3Code: 'SCR',
    numericCode: 690,
    name: 'Seychelles Rupee',
    minorUnitExponent: 2,
  ),
  'SDG': CurrencyMetadata(
    alpha3Code: 'SDG',
    numericCode: 938,
    name: 'Sudanese Pound',
    minorUnitExponent: 2,
  ),
  'SEK': CurrencyMetadata(
    alpha3Code: 'SEK',
    numericCode: 752,
    name: 'Swedish Krona',
    minorUnitExponent: 2,
  ),
  'SGD': CurrencyMetadata(
    alpha3Code: 'SGD',
    numericCode: 702,
    name: 'Singapore Dollar',
    minorUnitExponent: 2,
  ),
  'SHP': CurrencyMetadata(
    alpha3Code: 'SHP',
    numericCode: 654,
    name: 'Saint Helena Pound',
    minorUnitExponent: 2,
  ),
  'SLL': CurrencyMetadata(
    alpha3Code: 'SLL',
    numericCode: 694,
    name: 'Leone',
    minorUnitExponent: 2,
  ),
  'SOS': CurrencyMetadata(
    alpha3Code: 'SOS',
    numericCode: 706,
    name: 'Somali Shilling',
    minorUnitExponent: 2,
  ),
  'SRD': CurrencyMetadata(
    alpha3Code: 'SRD',
    numericCode: 968,
    name: 'Surinam Dollar',
    minorUnitExponent: 2,
  ),
  'SSP': CurrencyMetadata(
    alpha3Code: 'SSP',
    numericCode: 728,
    name: 'South Sudanese Pound',
    minorUnitExponent: 2,
  ),
  'STN': CurrencyMetadata(
    alpha3Code: 'STN',
    numericCode: 930,
    name: 'Dobra',
    minorUnitExponent: 2,
  ),
  'SVC': CurrencyMetadata(
    alpha3Code: 'SVC',
    numericCode: 222,
    name: 'El Salvador Colon',
    minorUnitExponent: 2,
  ),
  'SYP': CurrencyMetadata(
    alpha3Code: 'SYP',
    numericCode: 760,
    name: 'Syrian Pound',
    minorUnitExponent: 2,
  ),
  'SZL': CurrencyMetadata(
    alpha3Code: 'SZL',
    numericCode: 748,
    name: 'Lilangeni',
    minorUnitExponent: 2,
  ),
  'THB': CurrencyMetadata(
    alpha3Code: 'THB',
    numericCode: 764,
    name: 'Baht',
    minorUnitExponent: 2,
  ),
  'TJS': CurrencyMetadata(
    alpha3Code: 'TJS',
    numericCode: 972,
    name: 'Somoni',
    minorUnitExponent: 2,
  ),
  'TMT': CurrencyMetadata(
    alpha3Code: 'TMT',
    numericCode: 934,
    name: 'Turkmenistan New Manat',
    minorUnitExponent: 2,
  ),
  'TND': CurrencyMetadata(
    alpha3Code: 'TND',
    numericCode: 788,
    name: 'Tunisian Dinar',
    minorUnitExponent: 3,
  ),
  'TOP': CurrencyMetadata(
    alpha3Code: 'TOP',
    numericCode: 776,
    name: 'Pa\'anga',
    minorUnitExponent: 2,
  ),
  'TRY': CurrencyMetadata(
    alpha3Code: 'TRY',
    numericCode: 949,
    name: 'Turkish Lira',
    minorUnitExponent: 2,
  ),
  'TTD': CurrencyMetadata(
    alpha3Code: 'TTD',
    numericCode: 780,
    name: 'Trinidad and Tobago Dollar',
    minorUnitExponent: 2,
  ),
  'TWD': CurrencyMetadata(
    alpha3Code: 'TWD',
    numericCode: 901,
    name: 'New Taiwan Dollar',
    minorUnitExponent: 2,
  ),
  'TZS': CurrencyMetadata(
    alpha3Code: 'TZS',
    numericCode: 834,
    name: 'Tanzanian Shilling',
    minorUnitExponent: 2,
  ),
  'UAH': CurrencyMetadata(
    alpha3Code: 'UAH',
    numericCode: 980,
    name: 'Hryvnia',
    minorUnitExponent: 2,
  ),
  'UGX': CurrencyMetadata(
    alpha3Code: 'UGX',
    numericCode: 800,
    name: 'Uganda Shilling',
    minorUnitExponent: 0,
  ),
  'USD': CurrencyMetadata(
    alpha3Code: 'USD',
    numericCode: 840,
    name: 'US Dollar',
    minorUnitExponent: 2,
  ),
  'UYU': CurrencyMetadata(
    alpha3Code: 'UYU',
    numericCode: 858,
    name: 'Peso Uruguayo',
    minorUnitExponent: 2,
  ),
  'UZS': CurrencyMetadata(
    alpha3Code: 'UZS',
    numericCode: 860,
    name: 'Uzbekistan Sum',
    minorUnitExponent: 2,
  ),
  'VES': CurrencyMetadata(
    alpha3Code: 'VES',
    numericCode: 928,
    name: 'Bolívar Soberano',
    minorUnitExponent: 2,
  ),
  'VND': CurrencyMetadata(
    alpha3Code: 'VND',
    numericCode: 704,
    name: 'Dong',
    minorUnitExponent: 0,
  ),
  'VUV': CurrencyMetadata(
    alpha3Code: 'VUV',
    numericCode: 548,
    name: 'Vatu',
    minorUnitExponent: 0,
  ),
  'WST': CurrencyMetadata(
    alpha3Code: 'WST',
    numericCode: 882,
    name: 'Tala',
    minorUnitExponent: 2,
  ),
  'XAF': CurrencyMetadata(
    alpha3Code: 'XAF',
    numericCode: 950,
    name: 'CFA Franc BEAC',
    minorUnitExponent: 0,
  ),
  'XCD': CurrencyMetadata(
    alpha3Code: 'XCD',
    numericCode: 951,
    name: 'East Caribbean Dollar',
    minorUnitExponent: 2,
  ),
  'XOF': CurrencyMetadata(
    alpha3Code: 'XOF',
    numericCode: 952,
    name: 'CFA Franc BCEAO',
    minorUnitExponent: 0,
  ),
  'XPF': CurrencyMetadata(
    alpha3Code: 'XPF',
    numericCode: 953,
    name: 'CFP Franc',
    minorUnitExponent: 0,
  ),
  'YER': CurrencyMetadata(
    alpha3Code: 'YER',
    numericCode: 886,
    name: 'Yemeni Rial',
    minorUnitExponent: 2,
  ),
  'ZAR': CurrencyMetadata(
    alpha3Code: 'ZAR',
    numericCode: 710,
    name: 'Rand',
    minorUnitExponent: 2,
  ),
  'ZMW': CurrencyMetadata(
    alpha3Code: 'ZMW',
    numericCode: 967,
    name: 'Zambian Kwacha',
    minorUnitExponent: 2,
  ),
  'ZWL': CurrencyMetadata(
    alpha3Code: 'ZWL',
    numericCode: 932,
    name: 'Zimbabwe Dollar',
    minorUnitExponent: 2,
  ),
};
